os: linux
language: node_js
node_js:
  - node
cache:
  yarn: true
  directories:
    - "node_modules"
install:
  - yarn
before_deploy:
  - yarn build
deploy:
  provider: pages
  cleanup: false
  token: $GITHUB_TOKEN
  local_dir: packages/@logossim/page/build
  verbose: true
  on:
    branch: master